### ISSUE TITLE
AppleScript syntax error

### ISSUE THREAD

**Issue by drrnyip** [Didericis/itermp#1]
**Describe the bug**
running `itermp basic -d` produces the following error:
`Error: 104:110: syntax error: Expected end of line, etc. but found class name. (-2741)`

**Versions**
 - itermp version = 1.1.0
 - node version = 10.6.0
 - applescripts version = Applescript 2.7
 - bash version = GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
<img width="871" alt="screen shot 2018-07-17 at 12 10 36 am" src="https://user-images.githubusercontent.com/14695602/42802050-750259ba-8956-11e8-9e14-2eb40cb20c21.png">

**Comment by Didericis** [comment]
Hey, thanks for the bug report! Sorry it's taken a while to respond to this; if you have a version of iTerm2 that does not support applescripts, I believe it will cause the error you experienced. [This commit](https://github.com/Didericis/itermp/commit/b9ebf35eb6dab2c8ad179921f659c3cdf3ba1621) (in iTermp >= 1.1.1) should fix the issue. If it doesn't, you may also need to update to the latest version of iTerm2 (currently 3.2.0). If those updates don't solve the issue, let me know and I'll reopen the issue.
